(() => {
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const path=location.pathname.split('/').pop()||'index.html';
const routes={
 'index.html':['LA MOBILITÉ, À VOTRE PORTÉE','Votre prochain départ commence ici.','Un véhicule à acquérir, un emploi de chauffeur ou une voiture à confier : trouvez le parcours GM Fleet qui vous correspond.','img/fleet_white_bg.png','Choisir mon parcours'],
 'services.html':['NOS SOLUTIONS','Un parcours pour chaque ambition.','Choisissez votre situation. Nous vous guidons vers le service qui vous correspond.','img/fleet_white_bg.png','Choisir mon parcours'],
 'vehicules.html':['NOTRE FLOTTE','Trouvez votre prochain véhicule.','Découvrez les modèles proposés et consultez les conditions de candidature.','img/swift-official.png','Voir les véhicules'],
 'vehicule-credit.html':['VÉHICULE À CRÉDIT','Prenez le volant. Avancez vers la propriété.','Découvrez le parcours Drive to Own, les conditions et les véhicules. Préparez votre candidature à votre rythme.','img/swift-official.png','Commencer ma candidature'],
 'agregateur-yango.html':['PARTENAIRE YANGO','Vous conduisez. Nous vous accompagnons.','Rejoignez GM Fleet avec votre véhicule et votre compte Yango. Vous conservez votre voiture et votre activité.','img/ist-official.png','Rejoindre GM Fleet'],
 'gestion-flotte.html':['PROPRIÉTAIRES','Votre voiture, entre de bonnes mains.','Confiez l’exploitation de votre véhicule à GM Fleet. Vous restez propriétaire, nous assurons le suivi opérationnel.','img/blade-official.png','Faire évaluer ma voiture'],
 'recrutement-chauffeurs.html':['CHAUFFEURS PARTENAIRES','Votre expérience mérite une nouvelle route.','Conduisez les véhicules de notre flotte et développez votre activité. Commencez par une candidature simple.','img/swift-official.png','Postuler maintenant'],
 'apropos.html':['GEORGE MICHAEL LOGISTICS','Des personnes derrière chaque parcours.','Découvrez GM Fleet, notre activité à Kinshasa et les moyens de contacter notre équipe.','img/fleet_white_bg.png','Contacter l’équipe']
};
const labels={
 'index.html':['Comment ça marche','Nos services','Véhicules','Notre équipe','Notre vision'],
 'services.html':['Votre parcours','Nos offres','Équipements'],
 'vehicules.html':['Avec GM Fleet','Les véhicules','Témoignages','Votre parcours'],
 'vehicule-credit.html':['Le parcours','Accompagnement','Conditions','Candidature'],
 'agregateur-yango.html':['Les avantages','Votre activité','Le parcours','Inscription'],
 'gestion-flotte.html':['Les catégories','Notre gestion','GML Mobile','Réparations','Conditions','Évaluation'],
 'recrutement-chauffeurs.html':['Le parcours','Conditions','Candidature'],
 'apropos.html':['Notre histoire','Événements','Contact']
};
function initialize(){
 if(path==='detail-service.html'&&!location.search){location.replace('/services.html');return;}
 document.body.classList.add('public-site');
 if(path==='vehicules.html')document.body.classList.add('pub-catalogue');
 const oldNav=document.querySelector('body>nav');if(oldNav)oldNav.remove();
 document.querySelectorAll('body>a[href="/payer.html"]').forEach(a=>a.remove());
 const header=document.createElement('header');header.className='pub-header';header.innerHTML=`<div class="pub-nav"><a href="/index.html" class="pub-logo" aria-label="GM Fleet — Accueil"><img src="/img/gml-official.jpeg" alt="George Michael Logistics"><span class="pub-brand-copy"><strong>GM Fleet</strong><small>Une marque de GML</small></span></a><button class="pub-menu" aria-controls="public-navigation" aria-expanded="false">Menu ☰</button><nav id="public-navigation" class="pub-links" aria-label="Navigation principale">${[['index.html','Accueil'],['services.html','Nos services'],['vehicules.html','Véhicules'],['apropos.html','À propos & contact']].map(([url,name])=>`<a href="/${url}" ${path===url?'aria-current="page"':''}>${name}</a>`).join('')}<a href="/payer.html" class="pub-account">Mon espace chauffeur ↗</a></nav></div>`;document.body.prepend(header);
 const menu=header.querySelector('button'),links=header.querySelector('nav');menu.onclick=()=>{const open=links.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'Fermer ×':'Menu ☰';};header.addEventListener('keydown',e=>{if(e.key==='Escape'&&links.classList.contains('open')){menu.click();menu.focus();}});
 document.querySelectorAll('body>footer').forEach(f=>f.remove());const footer=document.createElement('footer');footer.className='pub-footer';footer.innerHTML='<div class="pub-footer-brand"><img src="/img/gml-official.jpeg" alt="GML"><div><strong>GM Fleet</strong> · Une marque de George Michael Logistics<br>Kinshasa, Gombe · 01, Ngongo Lutete</div></div><div class="pub-footer-links"><a href="tel:+243851686846">+243 851 686 846</a><a href="mailto:info@georgemichaellogistics.cd">Nous écrire</a><a href="/apropos.html#contact">Contact</a></div>';document.body.append(footer);
 // Make document fields usable with assistive technology without changing their data identifiers.
 document.querySelectorAll('input[id],select[id],textarea[id]').forEach(input=>{const label=input.parentElement.querySelector('label');if(label&&!label.htmlFor)label.htmlFor=input.id;});
 window.refreshPublicPanels?.(path);window.modernizePublicConfirmations?.();
 const sections=[...document.querySelectorAll('body>section')],meta=routes[path];
 if(meta&&sections.length){
  const originalHero=sections.shift();const hero=document.createElement('section');hero.className='pub-hero';hero.innerHTML=`<div><p class="pub-eyebrow">${meta[0]}</p><h1>${meta[1]}</h1><p>${meta[2]}</p><div class="pub-hero-actions"><button class="pub-button primary" id="pub-start">${meta[4]} <span aria-hidden="true">↗</span></button>${path==='services.html'?'':'<a class="pub-button" href="/services.html">Tous les services</a>'}</div></div><img class="pub-hero-image" src="/${meta[3]}" alt="Véhicules GM Fleet" fetchpriority="high">`;originalHero.replaceWith(hero);
  const explorer=document.createElement('main');explorer.className='pub-explorer';hero.after(explorer);
  if(window.setupPublicDirectory?.(path,hero,sections,explorer)){}else if(window.isPublicServicePage?.(path)){window.setupPublicServiceFlow(path,hero,sections,explorer);}else{
  const overview=document.createElement('section');overview.className='pub-overview';overview.id='pub-overview';
  if(['index.html','services.html'].includes(path))overview.innerHTML='<h2>Quel est votre projet ?</h2><p>Quatre parcours. Une équipe pour vous accompagner.</p>'+window.publicProfileCards();
  else overview.innerHTML='<h2>Les essentiels, avant de commencer.</h2><p>Consultez chaque rubrique sans perdre votre place.</p><div class="pub-facts">'+(path==='recrutement-chauffeurs.html'?[['Un parcours accompagné','Candidature, évaluation et intégration dans la flotte.'],['Préparez vos documents','Votre téléphone, votre expérience et votre CV ou permis.'],['À votre rythme','Complétez les étapes et vérifiez vos informations avant l’envoi.']]:path==='gestion-flotte.html'?[['Vous restez propriétaire','Notre équipe prend en charge le suivi opérationnel.'],['Une évaluation préalable','Présentez votre véhicule pour préparer son inspection.'],['Des conditions à consulter','Retrouvez les catégories et les conditions dans les rubriques ci-dessus.']]:path==='agregateur-yango.html'?[['Votre voiture reste la vôtre','Rejoignez le réseau sans confier votre véhicule en gestion.'],['Votre activité continue','Découvrez les avantages et le parcours de rattachement.'],['Une inscription guidée','Préparez vos informations et les documents de votre véhicule.']]:path==='apropos.html'?[['À Kinshasa','Une équipe locale pour les chauffeurs et propriétaires.'],['Plusieurs parcours','Financement, conduite, agrégation et gestion de flotte.'],['Parlons de votre projet','Appelez-nous ou préparez un message depuis la rubrique Contact.']]:[['Découvrez le parcours','Consultez les étapes et les conditions avant de postuler.'],['Choisissez votre véhicule','Explorez les modèles et leurs offres existantes.'],['Une candidature guidée','Préparez vos informations, puis vérifiez-les avant l’envoi.']]).map(([title,desc])=>`<div class="pub-fact"><strong>${title}</strong><p>${desc}</p></div>`).join('')+'</div>';
  const panels=[overview,...sections],names=['En bref',...(labels[path]||sections.map((s,i)=>'Rubrique '+(i+1)))];
  const nav=document.createElement('div');nav.className='pub-section-nav';nav.setAttribute('role','tablist');nav.setAttribute('aria-label','Rubriques de la page');const picker=document.createElement('label');picker.className='pub-section-select';picker.textContent='Explorer cette page';const select=document.createElement('select');select.setAttribute('aria-label','Rubrique affichée');picker.append(select);
  panels.forEach((panel,i)=>{if(!panel.id)panel.id='pub-section-'+i;panel.classList.add('pub-panel');panel.setAttribute('role','tabpanel');panel.setAttribute('aria-labelledby','pub-section-tab-'+i);nav.insertAdjacentHTML('beforeend',`<button type="button" role="tab" id="pub-section-tab-${i}" aria-controls="${panel.id}" data-panel="${i}">${esc(names[i]||'Découvrir')}</button>`);select.add(new Option(names[i]||'Découvrir',String(i)));});
  explorer.append(nav,picker,...panels);
  const show=(index,focus=false)=>{panels.forEach((panel,i)=>{panel.hidden=i!==index;const tab=nav.children[i];tab.setAttribute('aria-selected',String(i===index));tab.tabIndex=i===index?0:-1;});select.value=String(index);if(focus)nav.children[index].focus();};
  nav.onclick=e=>{const button=e.target.closest('[data-panel]');if(button)show(Number(button.dataset.panel));};nav.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const current=Number(select.value),next=e.key==='Home'?0:e.key==='End'?panels.length-1:(current+(e.key==='ArrowRight'?1:panels.length-1))%panels.length;show(next,true);};select.onchange=()=>show(Number(select.value));
  show(path==='vehicules.html'?2:0);
  function revealHash(){if(!location.hash)return;const target=document.getElementById(decodeURIComponent(location.hash.slice(1)));const index=panels.findIndex(p=>p===target||p.contains(target));if(index>=0){show(index);target.scrollIntoView({block:'start'});}}
  document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(!a)return;const target=document.getElementById(a.getAttribute('href').slice(1));const index=target?panels.findIndex(p=>p===target||p.contains(target)):-1;if(index>=0){show(index);requestAnimationFrame(()=>target.scrollIntoView({behavior:'smooth',block:'start'}));}});
  window.addEventListener('hashchange',revealHash);revealHash();
  document.getElementById('pub-start').onclick=()=>{let index=panels.findIndex(p=>p.querySelector('form'));if(path==='vehicules.html')index=2;if(path==='services.html')index=1;if(index<0)index=0;show(index);explorer.scrollIntoView({behavior:'smooth',block:'start'});};
  }
 }else{
  sections.forEach(s=>{s.classList.add('pub-panel');s.style.maxWidth='1144px';s.style.margin='auto';s.style.padding='24px 18px';});
 }
 // App links describe their real destinations; no simulated download.
 document.querySelectorAll('a').forEach(a=>{if(a.textContent.includes('Télécharger GML Mobile'))a.textContent='Demander un accès à GML Mobile';if(a.textContent.includes('Continuer dans GML Mobile'))a.textContent='Voir l’aperçu GML Mobile';});
 for(const form of document.querySelectorAll('#applicationForm,#serviceApplicationForm'))if(!form.querySelector('#dynamicFieldsContainer'))wizard(form);
 const contact=document.getElementById('contactForm');if(contact){const button=contact.querySelector('[type=submit]');if(button)button.textContent='Préparer mon e-mail';contact.insertAdjacentHTML('beforeend','<p class="pub-form-help">Votre application e-mail s’ouvrira. Le message sera envoyé uniquement après votre validation dans cette application. Vous pouvez aussi nous appeler au +243 851 686 846.</p>');contact.addEventListener('submit',e=>{e.preventDefault();e.stopImmediatePropagation();if(!contact.reportValidity())return;const subject=document.getElementById('contactSujet').value,body=['Nom : '+document.getElementById('contactName').value,'Téléphone : '+document.getElementById('contactPhone').value,document.getElementById('contactMessage').value].join('\n');location.href='mailto:info@georgemichaellogistics.cd?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);},true);}
}
function wizard(form){
 const fields=[...form.querySelectorAll('input:not([type=hidden]),select,textarea')],submit=form.querySelector('[type=submit]');if(!fields.length||!submit)return;
 const definitions=form.id==='applicationForm'?[['Vos informations',['clientName','clientPhone','clientAddress','planDuration','clientExperience']],['Votre co-emprunteur',['coBorrowerName','coBorrowerPhone','coBorrowerAddress']],['Vos documents',['clientPermisUpload']]]:fields.some(f=>f.id==='flotteCarBrand')?[['Vos coordonnées',['applicantName','applicantPhone','applicantAddress','flotteEmail','flotteID']],['Votre véhicule',['flotteCarBrand','flotteCarModel','flotteCarYear','flotteCarPlate','flotteCarChassis']],['Vos documents',['flotteCarteRose','flottePhotos']]]:[['Vos coordonnées',['applicantName','applicantFirstName','applicantLastName','applicantPhone','applicantAddress','applicantCommune']],['Votre profil et vos documents',fields.filter(f=>!/applicant(Name|FirstName|LastName|Phone|Address|Commune)$/.test(f.id)).map(f=>f.id)]];
 const original=[...form.children],panels=[],assigned=new Set();form.noValidate=true;form.classList.add('pub-wizard');form.parentElement.classList.add('pub-form-shell');if(form.previousElementSibling)form.previousElementSibling.classList.add('pub-form-intro');
 const progress=document.createElement('div');progress.className='pub-progress';progress.setAttribute('aria-live','polite');form.append(progress);
 for(const [title,ids] of definitions){const selected=fields.filter(f=>ids.includes(f.id));if(!selected.length)continue;const panel=document.createElement('section');panel.className='pub-step';panel.innerHTML='<h3 tabindex="-1">'+esc(title)+'</h3><div class="pub-fields"></div>';for(const field of selected){let wrapper=field.parentElement;while(wrapper!==form&&(!wrapper.querySelector('label')||wrapper.querySelectorAll('input:not([type=hidden]),select,textarea').length>1)){if(wrapper.querySelectorAll('input:not([type=hidden]),select,textarea').length>1){wrapper=field.parentElement;break;}wrapper=wrapper.parentElement;}if(wrapper===form){wrapper=document.createElement('div');field.before(wrapper);wrapper.append(field);}panel.querySelector('.pub-fields').append(wrapper);assigned.add(field);}panels.push(panel);form.append(panel);}
 for(const field of fields.filter(f=>!assigned.has(f)))panels.at(-1).querySelector('.pub-fields').append(field.parentElement);
 const review=document.createElement('section');review.className='pub-step';review.innerHTML='<h3 tabindex="-1">Vérifiez votre candidature</h3><p class="pub-form-help">Vérifiez les informations et les documents. Utilisez Retour pour les modifier avant l’envoi.</p><dl class="pub-review"></dl>';panels.push(review);form.append(review);
 const actions=document.createElement('div');actions.className='pub-wizard-actions';const back=document.createElement('button'),next=document.createElement('button');back.type=next.type='button';back.className='pub-button';next.className='pub-button primary';back.textContent='← Retour';next.textContent='Continuer →';submit.className='pub-button primary';actions.append(back,next,submit);form.append(actions);
 const error=document.createElement('p');error.className='pub-form-error';error.setAttribute('role','alert');form.append(error);
 // Keep hidden payload fields in the form, but remove the emptied presentation wrappers.
 for(const element of original){if(element.tagName==='INPUT'&&element.type==='hidden')continue;for(const input of element.querySelectorAll('input[type=hidden]'))form.prepend(input);if(!element.contains(progress)&&element.parentElement===form)element.remove();}
 const stepOffset=document.querySelector('.vehicle-choice')&&form.id==='applicationForm'?1:0;
 let index=0;const show=(i,focus=true)=>{index=i;panels.forEach((p,n)=>p.hidden=n!==i);progress.innerHTML='<span>Étape '+(i+1+stepOffset)+' sur '+(panels.length+stepOffset)+'</span><progress max="'+(panels.length+stepOffset)+'" value="'+(i+1+stepOffset)+'" aria-label="Avancement de la candidature"></progress>';back.hidden=i===0;next.hidden=i===panels.length-1;submit.hidden=i!==panels.length-1;error.textContent='';if(i===panels.length-1){review.querySelector('dl').innerHTML=fields.map(f=>{const label=document.querySelector('label[for="'+f.id+'"]')?.textContent.trim()||f.id;const value=f.type==='file'?[...f.files].map(x=>x.name).join(', '):f.tagName==='SELECT'?f.selectedOptions[0]?.textContent:f.value;return '<div><dt>'+esc(label)+'</dt><dd>'+esc(value||'Non renseigné')+'</dd></div>';}).join('');}if(focus){panels[i].querySelector('h3').focus({preventScroll:true});form.scrollIntoView({behavior:'smooth',block:'start'});}};
 const invalid=panel=>[...panel.querySelectorAll('input,select,textarea')].find(f=>!f.checkValidity());next.onclick=()=>{const field=invalid(panels[index]);if(field){field.reportValidity();return;}show(index+1);};back.onclick=()=>show(index-1);
 form.addEventListener('submit',e=>{for(let i=0;i<panels.length-1;i++){const field=invalid(panels[i]);if(field){e.preventDefault();e.stopImmediatePropagation();show(i);field.reportValidity();return;}}if(index<panels.length-1){e.preventDefault();e.stopImmediatePropagation();show(index+1);}},true);
 form.addEventListener('reset',()=>setTimeout(()=>{show(0,false);form.querySelectorAll('.pub-file-info').forEach(p=>p.textContent='');},0));
 for(const file of fields.filter(f=>f.type==='file')){const info=document.createElement('p');info.className='pub-file-info';info.setAttribute('aria-live','polite');file.after(info);file.addEventListener('change',()=>{info.textContent=[...file.files].map(f=>f.name+' · '+(f.size/1024/1024).toFixed(1)+' Mo').join(' / ');});}
 form.addEventListener('gmfleet-error',e=>{error.textContent=e.detail;});show(0,false);
}
function start(){
 try{initialize();document.documentElement.classList.remove('public-ui-pending','public-ui-failed');}
 catch(error){window.publicUIFailed?.();console.error('Public UI initialization failed',error);}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
