const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..');
function fixture(){
 const data={contract_id:'contract',driver_name:'Driver Test',currency:'USD',vehicle:{model:'Toyota Corolla',plate:'TEST123'},daily_amount:10,due:10,total_remaining:100,attempts:[]};window.calls=[];
 window.supabase={createClient:()=>({auth:{signOut:async()=>({}),signInWithOtp:async({phone})=>{window.otpPhone=phone;return {};},verifyOtp:async()=>({})},functions:{invoke:async(name,{body})=>{window.calls.push(body);if(body.action==='phone-login')return {data:{token:'b'.repeat(64)}};if(body.action==='pay'){data.attempts=[{id:body.id,reference:'GMTEST',amount:Number(body.amount),transaction_fee:0.3,total_charged:10.3,currency:'USD',provider:body.provider,state:'pending'}];}if(body.action==='check'){data.attempts[0].state='approved';data.attempts[0].receipt_id=123;data.total_remaining=90;data.due=0;}return {data:JSON.parse(JSON.stringify(data))};}}})};
}
(async()=>{const server=http.createServer((req,res)=>{const file=path.join(root,new URL(req.url,'http://localhost').pathname);try{res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});try{const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*supabase.co/**',r=>r.abort());await page.route('**/supabase-js@*/**',r=>r.fulfill({contentType:'text/javascript',body:'('+fixture.toString()+')();'}));const base='http://127.0.0.1:'+server.address().port;
 await page.goto(base+'/payer.html');await page.locator('#phoneForm').waitFor();assert.equal(await page.locator('#driverPayForm').count(),0);
 await page.locator('[name=phone]').fill('0812345678');await page.getByRole('button',{name:'Recevoir le code SMS'}).click();await page.locator('[name=code]').fill('123456');await page.getByRole('button',{name:'Voir mes versements'}).click();await page.getByText('Véhicule : Toyota Corolla',{exact:false}).waitFor();assert.equal(await page.evaluate(()=>window.otpPhone),'+243812345678');assert.match(await page.locator('#feeSummary').innerText(),/10,30/);await page.locator('[name=wallet]').fill('+243810000000');await page.locator('[name=amount]').fill('10');await page.getByRole('button',{name:'Payer maintenant'}).click();await page.locator('#checkPayment').waitFor();assert.equal(await page.locator('#driverPayForm').count(),0);assert.equal((await page.evaluate(()=>window.calls.filter(c=>c.action==='pay'))).length,1);
 await page.locator('#checkPayment').click();await page.getByText('Paiement confirmé',{exact:false}).waitFor();await page.getByText('Reçu #123',{exact:false}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(new URL(page.url()).hash,'');await page.locator('#changeDriver').click();await page.locator('#phoneForm').waitFor();await page.goto(base+'/payer.html#token='+'a'.repeat(64));await page.locator('#driverPayForm').waitFor();assert.deepEqual(errors,[]);await page.screenshot({path:path.join(__dirname,'araka-driver-mobile.png'),fullPage:true});console.log('PASS: private link required, actual pay form submission, pending blocks another payment, verified receipt shown, token removed from URL and mobile layout fits.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exit(1)});
