const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const raw=fs.readFileSync('supabase/functions/araka-payments/index.ts','utf8');
const source=raw.replace(/^import .*;\r?\n/,'').replaceAll('body?:unknown','body').replace(/:(number|string|unknown|any)\b/g,'').replaceAll(/Deno\.env\.get\(([^)]+)\)!/g,'Deno.env.get($1)');
const cap='a'.repeat(64),callback='b'.repeat(64),sha=v=>require('crypto').createHash('sha256').update(v).digest('hex');
async function run({action='check',providerData={transactionId:'TX-1',statusCode:200,statusDescription:'APPROVED'},dispatch=true,sandbox=false,invalidCallback=false,transactionId='TX-1',recent=false,identity=null,lookupResult={ok:true},initiationData={transactionId:"TX-1",statusCode:202,statusDescription:"ACCEPTED"},initiationThrows=false,routeStatus=405,pageId="test-page",baseUrl,staff={role:"admin",active:true}}={}){
 let handler,charges=0,updates=[];const attempt={id:'11111111-1111-4111-8111-111111111111',contract_id:'contract',reference:'GMTEST',amount:10,transaction_fee:0.3,total_charged:10.3,currency:'USD',provider:'MPESA',wallet:'+243810000000',state:'pending',transaction_id:transactionId,callback_hash:sha(callback),last_checked_at:recent?new Date().toISOString():null};
 const snapshot=()=>({contract_id:'contract',driver_name:'Driver',currency:'USD',daily_amount:10,total_remaining:100,due:10,attempts:[{...attempt}]});
 const db={auth:{getUser:async()=>({data:{user:identity},error:identity?null:{message:'invalid'}})},rpc:async(name,{p}={})=>{if(name==='issue_driver_plate_access'){updates.push(p);return {data:lookupResult};}if(name==='driver_payment_receipt'){updates.push(p);return {data:{status:'confirmed'}};}if(name==='driver_payment_context')return {data:snapshot()};if(name==='begin_araka_payment')return {data:{...attempt,dispatch,driver_name:'Driver'}};if(name==='record_araka_status'){updates.push(p);if(p.status==='APPROVED')attempt.state='approved';return {data:attempt.state};}throw Error(name);},from:table=>({select:()=>({eq(){return this;},maybeSingle:async()=>({data:table==="staff_members"?staff:invalidCallback?null:attempt})})})};
 const env={ARAKA_BASE_URL:baseUrl||(sandbox?'https://araka-api-uat.azurewebsites.net':'https://api.arakapay.com'),ARAKA_EMAIL:'fake@example.test',ARAKA_PASSWORD:'test-placeholder',ARAKA_PAYMENT_PAGE_ID:pageId};
 vm.runInNewContext(source,{Deno:{env:{get:n=>env[n]||n},serve:f=>handler=f},Response,Request,URL,TextEncoder,Uint8Array,crypto,AbortSignal,createClient:()=>db,fetch:async(url,options)=>{if(baseUrl?.includes('merchant.arakapay.com'))assert.equal(new URL(url).hostname,'api.arakapay.com');if(url.endsWith('/api/login'))return Response.json({token:'test-token'});if(url.endsWith('/api/pay/paymentrequest')&&options.method==='GET')return new Response(null,{status:routeStatus});if(url.endsWith('/api/pay/paymentrequest')){charges++;const body=JSON.parse(options.body);assert.equal(body.order.amount,10.3);assert.equal(body.order.currency,'USD');assert.equal(body.order.paymentPageId,'test-page');assert.equal(body.order.customerPhoneNumber,'243810000000');assert.equal(body.paymentChannel.walletID,'243810000000');assert.equal(body.paymentChannel.channel,'MOBILEMONEY');if(initiationThrows)throw Error('timeout');return Response.json(initiationData);}return Response.json(providerData);}});
 const url=action==='callback'?'https://test?callback='+callback:'https://test';
 const response=await handler(new Request(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action==='callback'?{statusCode:200,statusDescription:'APPROVED'}:{action,phone:"0812345678",plate:"AB123",receipt_id:123,token:cap,id:attempt.id,amount:'10',provider:'MPESA',wallet:attempt.wallet})}));
 return {status:response.status,data:await response.json(),charges,updates};
}
(async()=>{
 for(const suffix of ['', '/', '/api', '/api/', '/swagger', '/swagger/index.html', '/swagger/index.html#/payments', '/swagger/v1/swagger.json']){const result=await run({action:'pay',baseUrl:'https://api.arakapay.com'+suffix});assert.equal(result.status,200,suffix);assert.equal(result.charges,1,suffix);}
 for(const baseUrl of ['http://api.arakapay.com','https://evil.example/swagger','https://api.arakapay.com/unknown','https://api.arakapay.com/?key=secret'])assert.equal((await run({action:'pay',baseUrl})).charges,0);
 assert.equal((await run({action:'staff-check'})).status,401);
 assert.equal((await run({action:'staff-check',identity:{id:'admin'},staff:{role:'agent',active:true}})).status,403);
 const checked=await run({action:'staff-check',identity:{id:'admin'},recent:true,baseUrl:'https://api.arakapay.com/swagger/index.html'});assert.equal(checked.data.state,'approved');assert.equal(checked.charges,0);
 assert.equal((await run({action:'staff-check',identity:{id:'admin'},providerData:{error:'unavailable'}})).status,400);
 for(const baseUrl of ['https://merchant.arakapay.com/auth/login','https://merchant.arakapay.com/','https://pcesarakapayprodapi01.eastus.cloudapp.azure.com']){const result=await run({action:'pay',baseUrl});assert.equal(result.status,200,baseUrl);assert.equal(result.charges,1);}
 for(const options of [{initiationData:{statusCode:403,statusDescription:'Validation Error'}},{initiationThrows:true}]){const failed=await run({action:'pay',...options});assert.equal(failed.status,400);assert.match(failed.data.error,/Araka/);assert.equal(failed.charges,1);assert.equal(failed.updates.length,0);}
 const unavailable=await run({action:'pay',baseUrl:'https://pcesarakapayprodapi01.eastus.cloudapp.azure.com',routeStatus:404});assert.equal(unavailable.status,400);assert.equal(unavailable.charges,0);assert.match(unavailable.data.error,/API e-commerce/);
 const pageUrl=await run({action:'pay',baseUrl:'https://merchant.arakapay.com/auth/login',pageId:'https://merchant.arakapay.com/payment/test-page/'});assert.equal(pageUrl.status,200);
 const arrayApproved=await run({providerData:[{transactionId:'OTHER',statusCode:200,status:'APPROVED'},{transactionId:'TX-1',statusCode:200,status:'APPROVED',amount:10.3,currency:'USD'}]});assert.ok(arrayApproved.updates.some(p=>p.status==='APPROVED'));
 const arrayAccepted=await run({providerData:[{transactionId:'TX-1',statusCode:202,status:'ACCEPTED'}]});assert.ok(arrayAccepted.updates.every(p=>p.status!=='APPROVED'));
 const arrayRecovery=await run({transactionId:null,providerData:[{transactionId:'TX-1',transactionReference:'GMTEST',statusCode:200,status:'APPROVED'}]});assert.ok(arrayRecovery.updates.some(p=>p.status==='APPROVED'));
 for(const status of ['DECLINED','FAILED','CANCELLED','EXPIRED']){const failed=await run({providerData:{transactionId:'TX-1',statusCode:400,status}});assert.ok(failed.updates.some(p=>p.status==='DECLINED'));}
 const rejected=await run({action:'pay',initiationData:{statusCode:400,statusDescription:'DECLINED'}});assert.ok(rejected.updates.some(p=>p.status==='DECLINED'));assert.equal(rejected.charges,1);
 const phone=await run({action:'driver-lookup'});assert.equal(phone.status,200);assert.match(phone.data.token,/^[a-f0-9]{64}$/);assert.equal(phone.updates[0].phone,'0812345678');assert.equal(phone.updates[0].plate,'AB123');assert.equal(phone.charges,0);
 assert.equal((await run({action:'driver-lookup',lookupResult:{error:'Mismatch'}})).status,400);
 assert.equal((await run({action:'driver-lookup',lookupResult:{error:'Too many',limited:true}})).status,429);
 const slip=await run({action:'receipt'});assert.equal(slip.data.status,'confirmed');assert.equal(slip.updates[0].token_hash,sha(cap));assert.equal(slip.updates[0].receipt_id,123);assert.equal(slip.charges,0);
 assert.ok((await run({providerData:{transactionId:'TX-1',statusCode:200,statusDescription:'APPROVED',amount:10.3}})).updates.some(p=>p.status==='APPROVED'));
 assert.ok((await run()).updates.some(p=>p.status==='APPROVED'));
 const accepted=await run({action:'pay'});assert.equal(accepted.charges,1);assert.ok(accepted.updates.every(p=>p.status!=='APPROVED'));
 assert.equal((await run({action:'pay',dispatch:false})).charges,0);
 assert.equal((await run({action:'pay',sandbox:true})).status,409);
 const forged=await run({action:'callback',recent:true,providerData:{transactionId:'TX-1',statusCode:202,statusDescription:'PENDING'}});assert.ok(forged.updates.every(p=>p.status!=='APPROVED'));
 assert.ok((await run({action:'callback',recent:true})).updates.some(p=>p.status==='APPROVED'));
 assert.equal((await run({action:'callback',invalidCallback:true})).status,401);
 for(const providerData of [{transactionId:'OTHER',statusCode:200,statusDescription:'APPROVED'},{transactionId:'TX-1',statusCode:200,statusDescription:'APPROVED',amount:10},{transactionId:'TX-1',statusCode:200,statusDescription:'APPROVED',currency:'CDF'}])assert.equal((await run({providerData})).updates.length,0);
 assert.equal((await run({transactionId:null,providerData:{transactionId:'TX-1',originatingTransactionId:'OTHER',statusCode:200,statusDescription:'APPROVED'}})).updates.length,0);
 assert.ok((await run({transactionId:null,providerData:{transactionId:'TX-1',originatingTransactionId:'GMTEST',statusCode:200,statusDescription:'APPROVED'}})).updates.some(p=>p.status==='APPROVED'));
 console.log('PASS: only matching provider-approved transactions credit the ledger; 202, forged callbacks, wrong amounts/currency/IDs cannot; retries do not recharge; sandbox collection blocked.');
})().catch(e=>{console.error(e);process.exit(1)});
