const {chromium}=require(process.env.PLAYWRIGHT_MODULE),http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const original=fs.readFileSync('tests/finance-browser.cjs','utf8');const fixtureSource=original.slice(original.indexOf('function fixture()'),original.indexOf('(async()=>'));
function dashboardFixture(){
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Kinshasa',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const before=new Date(today+'T12:00:00Z');before.setUTCDate(before.getUTCDate()-1);const yesterday=before.toISOString().slice(0,10),t=window.fixtureTables;
 t.contracts.push({id:'a',application_id:1,driver_id:'d',vehicle_id:1,status:'active',currency:'USD',signed_reference:'TEST-A',daily_lolc:27,daily_gml:2.5,start_date:yesterday,end_date:'2027-09-23',operating_days:[1,2,3,4,5,6],contract_type:'DRIVE_TO_OWN'});t.drivers.push({id:'d',full_name:'Driver Test',phone:'123'});t.vehicles.push({id:1,model:'Swift',plate:'TEST-001',status:'En location'});
 for(let i=0;i<1001;i++)t.repayment_schedules.push({id:i+1,contract_id:'a',due_on:i===0?yesterday:i===1000?today:'2099-01-01',lolc_due:27,gml_due:2.5});
 t.payments.push({id:1,contract_id:'a',amount:10,lolc_amount:9,entry_kind:'payment',paid_on:today,created_at:new Date().toISOString(),driver_name:'Driver Test',reference:'CASH-1',method:'Espèces'});t.payment_allocations.push({payment_id:1,schedule_id:1,amount:10});t.araka_attempts.push({id:'p',contract_id:'a',reference:'PENDING',state:'pending',created_at:new Date().toISOString(),amount:99,currency:'USD'});
 t.applications[0].follow_up_on=yesterday;
 const create=window.supabase.createClient;window.supabase.createClient=(...args)=>{const db=create(...args),from=db.from;db.from=name=>{const q=from(name),then=q.then.bind(q);q.then=(ok,bad)=>{if(window.failFinance&&name==='contracts')return Promise.resolve({data:null,error:{message:'Test unavailable'}}).then(ok,bad);if(window.failCore&&name==='applications')return Promise.resolve({data:null,error:{message:'Core unavailable'}}).then(ok,bad);return then(ok,bad);};return q;};return db;};
}
(async()=>{const server=http.createServer((req,res)=>{try{const f=path.join(process.cwd(),new URL(req.url,'http://x').pathname);res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(f));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,r));const b=await chromium.launch({headless:true,channel:'msedge'});try{const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/vendor/supabase-2.57.4.js',r=>r.fulfill({contentType:'text/javascript',body:fixtureSource+';fixture();('+dashboardFixture.toString()+')();'}));await p.route('**/*supabase.co/**',r=>r.abort());await p.goto('http://localhost:'+server.address().port+'/admin.html');await p.locator('.dashboard-heading').waitFor();assert.match(await p.locator('[data-metric=due]').innerText(),/29,50/);assert.match(await p.locator('[data-metric=arrears]').innerText(),/19,50/);assert.match(await p.locator('[data-metric=received]').innerText(),/10,00/);assert.match(await p.locator('[data-metric=lolc]').innerText(),/9,00/);assert.match(await p.locator('#content').innerText(),/1 paiement\(s\) Mobile Money/);assert.equal(await p.locator('#content img').count(),0);
await p.screenshot({path:'tests/artifacts/admin-dashboard-desktop.png',fullPage:true});await p.setViewportSize({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'tests/artifacts/admin-dashboard-mobile.png',fullPage:true});
await p.locator('[data-dashboard-contract]').click();await p.locator('#financeDialog[open]').waitFor();assert.match(await p.locator('#financeDialog').innerText(),/Driver Test/);await p.locator('[data-finance-close]').click();await p.evaluate(()=>fixtureTables.payments.push({...fixtureTables.payments[0],id:2,amount:5,lolc_amount:4,reference:'CASH-2'}));await p.locator('nav [data-view=overview]').click();await p.waitForFunction(()=>document.querySelector('[data-metric=received]')?.textContent.includes('15,00'));
await p.locator('[data-stage-filter=new]').click();assert.equal(await p.locator('#stageFilter').inputValue(),'new');await p.locator('nav [data-view=overview]').click();await p.locator('.dashboard-heading').waitFor();await p.evaluate(()=>window.failFinance=true);await p.locator('#refresh').click();await p.locator('.dashboard-warning').waitFor();assert.match(await p.locator('#syncStatus').innerText(),/partielle/);assert.match(await p.locator('[data-metric=received]').innerText(),/15,00/);await p.evaluate(()=>window.failFinance=false);await p.locator('[data-dashboard-refresh]').click();await p.waitForFunction(()=>!document.querySelector('.dashboard-warning'));
await p.evaluate(()=>{fixtureTables.payments.push({...fixtureTables.payments[0],id:3,amount:2,lolc_amount:1,reference:'CASH-3'});window.dispatchEvent(new Event('focus'));});await p.waitForFunction(()=>document.querySelector('[data-metric=received]')?.textContent.includes('17,00'));
await p.evaluate(()=>window.failCore=true);await p.locator('#refresh').click();await p.waitForFunction(()=>document.querySelector('#syncStatus').textContent.includes('interrompue'));await p.evaluate(()=>window.failCore=false);
const firstFailure=await b.newPage();await firstFailure.route('**/vendor/supabase-2.57.4.js',r=>r.fulfill({contentType:'text/javascript',body:fixtureSource+';fixture();('+dashboardFixture.toString()+')();window.failFinance=true;'}));await firstFailure.route('**/*supabase.co/**',r=>r.abort());await firstFailure.goto('http://localhost:'+server.address().port+'/admin.html');await firstFailure.locator('.dashboard-warning').waitFor();assert.match(await firstFailure.locator('[data-metric=received]').innerText(),/Indisponible/);assert.ok(await firstFailure.locator('#workspace').isVisible());await firstFailure.close();assert.deepEqual(errors,[]);console.log('PASS dashboard pagination, totals, drilldown, navigation refresh, focus refresh, stale finance warning, recovery, core error and responsive layouts.');}finally{await b.close();server.close();}})().catch(e=>{console.error(e);process.exit(1)});
