const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
let fixture=fs.readFileSync(path.join(__dirname,'finance-browser.cjs'),'utf8').split('function fixture(){')[1].split('\n(async()=>')[0];
fixture='function fixture(){'+fixture;
fixture=fixture.replace("if(this.mode==='update')items.forEach(r=>Object.assign(r,this.payload,{revision:r.revision+1}));",`if(this.mode==='update')items.forEach(r=>{Object.assign(r,this.payload,{revision:r.revision+1});if(this.payload.review_status){r.process_step=this.payload.review_status==='accepted'?'appointment':'review';r.workflow_stage=this.payload.review_status==='accepted'?'contacted':'rejected';tables.operations_notifications.push({id:crypto.randomUUID(),application_id:r.id,channel:'sms_draft',kind:r.review_status,recipient:r.phone,body:'Bonjour, votre dossier GML a été traité. Aucun SMS envoyé.'});}});`);
fixture=fixture.replace("return {error:{message:'Unknown test RPC'}};",`if(name==='onboard_owner_vehicle'){tables.vehicles.push({id:99,model:p.model,plate:p.plate,vin:p.vin,tracker_id:p.tracker_id,status:'Disponible',owner_application_id:p.application_id});tables.applications.find(a=>a.id===p.application_id).preparation.fleet_joined_on=p.fuel_paid_on;return {data:99};}return {error:{message:'Unknown test RPC'}};`);
const seed=`const t=window.fixtureTables,b={...t.applications[0],lifecycle_version:2,review_status:'pending',process_step:'review',preparation:{},service_details:{}};
t.applications=[{...b,id:1,name:'Car na ngai candidat',program_type:'DRIVE_TO_OWN'},{...b,id:2,name:'Chauffeur candidat',program_type:'PARTNER_DRIVER'},{...b,id:3,name:'Propriétaire candidat',program_type:'FLEET_OWNER',service_details:{carModel:'Toyota IST',carPlate:'TEST-OWNER',carChassis:'VIN-OWNER'}},{...b,id:4,name:'Yango candidat',program_type:'YANGO'},{...b,id:5,name:'Refus candidat',program_type:'YANGO'}];`;
(async()=>{
 const server=http.createServer((req,res)=>{const file=path.join(root,new URL(req.url,'http://localhost').pathname);try{res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end();}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/vendor/supabase-2.57.4.js',r=>r.fulfill({contentType:'text/javascript',body:`(${fixture})();${seed}`}));
  await page.route('**/supabase.co/**',r=>r.abort());
  await page.goto(`http://127.0.0.1:${server.address().port}/admin.html`);await page.locator('#workspace').waitFor();
  const nav=async v=>page.locator(`nav [data-view="${v}"]`).click();
  await nav('applications');assert.equal(await page.locator('tbody tr').count(),5);
  await page.locator('[data-program-key="YANGO"]').click();assert.equal(await page.locator('tbody tr').count(),2);
  await page.getByRole('button',{name:'Refus candidat',exact:true}).click();
  assert.equal(await page.locator('#case-panel-process').isVisible(),false);
  await page.locator('#reviewForm [name=review_status]').selectOption('rejected');await page.locator('#reviewForm button').click();await page.getByText('Indiquez le motif du refus.',{exact:true}).waitFor();
  await page.locator('#reviewForm textarea').fill('Permis non valide');await page.locator('#reviewForm button').click();await page.getByRole('heading',{name:'Candidature refusée'}).waitFor();await page.locator('[data-close=caseDialog]').click();
  assert.equal(await page.locator('tbody tr').count(),1);
  await page.locator('[data-queue=rejected]').click();assert.equal(await page.locator('tbody tr').count(),1);
  await nav('applications');await page.screenshot({path:path.join(__dirname,'artifacts/lifecycle-inbox.png'),fullPage:true});
  const accept=async(name)=>{await nav('applications');await page.getByRole('button',{name,exact:true}).click();await page.locator('#reviewForm button').click();await page.waitForFunction(()=>!document.querySelector('#reviewForm'));};
  await accept('Car na ngai candidat');assert.equal(await page.locator('#case-panel-appointments').isVisible(),true);
  assert.match(await page.locator('.sms-drafts').innerText(),/brouillons uniquement/);
  await page.locator('#case-tab-process').click();
  for(const key of ['account_opened','lolc_eligible','vehicle_found','gml_inspected','lolc_inspected','client_validated','vehicle_received','tracker','paperwork','yango'])await page.locator(`#workflowForm [name=${key}]`).check();
  await page.locator('#workflowForm [name=lolc_status]').selectOption('approved');await page.locator('#workflowForm [name=process_step]').selectOption('handover');await page.locator('#workflowForm [name=handover_on]').fill('2026-09-23');await page.locator('#workflowForm button').click();
  await page.waitForFunction(()=>window.fixtureTables.applications[0].process_step==='handover');
  await page.screenshot({path:path.join(__dirname,'artifacts/lifecycle-dto.png'),fullPage:true});await page.locator('[data-close=caseDialog]').click();
  await accept('Chauffeur candidat');await page.locator('#case-tab-process').click();
  for(const key of ['interview_passed','driving_test_passed','training_completed'])await page.locator(`#workflowForm [name=${key}]`).check();
  await page.locator('#workflowForm [name=process_step]').selectOption('allocation');await page.locator('#workflowForm button').click();await page.waitForFunction(()=>window.fixtureTables.applications[1].process_step==='allocation');await page.locator('[data-close=caseDialog]').click();
  await accept('Propriétaire candidat');await page.locator('#case-tab-process').click();
  await page.locator('#workflowForm [name=process_step]').selectOption('ready');for(const input of await page.locator('#workflowForm input[type=checkbox]').all())await input.check();await page.locator('#workflowForm button').click();await page.locator('#ownerFleetForm').waitFor();
  await page.locator('#ownerFleetForm [name=tracker_id]').fill('TRACKER-TEST');await page.locator('#ownerFleetForm [name=fuel_reference]').fill('CASH-TEST');await page.locator('#ownerFleetForm [name=fuel_paid_on]').fill('2026-09-24');await page.locator('#ownerFleetForm input[type=checkbox]').check();await page.locator('#ownerFleetForm button').click();await page.waitForFunction(()=>window.fixtureTables.vehicles.length===1);await page.locator('[data-close=caseDialog]').click();
  await accept('Yango candidat');assert.equal(await page.locator('#case-panel-process').isVisible(),true);await page.locator('#workflowForm [name=process_step]').selectOption('joined');await page.locator('[name=invitation_explained]').check();await page.locator('[name=yango_joined]').check();await page.locator('#workflowForm button').click();await page.waitForFunction(()=>window.fixtureTables.applications[3].process_step==='joined');await page.locator('[data-close=caseDialog]').click();
  await nav('fleet');await page.getByRole('heading',{name:'Chauffeurs partenaires Yango · 1'}).waitFor();await page.getByText('TEST-OWNER',{exact:true}).waitFor();assert.match(await page.locator('#content').innerText(),/API Yango non connectée/);
  await page.screenshot({path:path.join(__dirname,'artifacts/lifecycle-fleet.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});await nav('applications');await page.screenshot({path:path.join(__dirname,'artifacts/lifecycle-mobile.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile has no page overflow');
  await nav('preparation');await page.getByRole('button',{name:'Chauffeur candidat',exact:true}).click();await page.locator('#case-tab-process').click();await page.screenshot({path:path.join(__dirname,'artifacts/lifecycle-case-mobile.png'),fullPage:true});assert.ok(await page.locator('#caseDialog').evaluate(e=>e.scrollWidth<=e.clientWidth),'dossier fits mobile');
  assert.deepEqual(errors,[]);console.log('PASS lifecycle: categories, review/refusal, routed tabs, four program checklists, owner fleet intake, confirmed Yango count, unsent drafts and mobile fit.');
 }finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
